# Flutter Analysis Options
# This file configures the analyzer to provide feedback on code quality

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  
  errors:
    # Suppress non-critical warnings
    deprecated_member_use: ignore
    unused_element: ignore
    unused_import: ignore
    unused_local_variable: ignore
    unused_field: ignore
    depend_on_referenced_packages: ignore
    unrelated_type_equality_checks: ignore
    avoid_types_as_parameter_names: ignore
    unnecessary_import: ignore
    unnecessary_to_list_in_spreads: ignore
    prefer_interpolation_to_compose_strings: ignore
    dead_null_aware_expression: ignore
    use_build_context_synchronously: ignore
    invalid_null_aware_operator: ignore
    unnecessary_null_comparison: ignore
    avoid_web_libraries_in_flutter: ignore
    unnecessary_non_null_assertion: ignore
    
  # Language features
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

linter:
  rules:
    # Disable cosmetic lint rules
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_declarations: false
    prefer_final_fields: false
    prefer_single_quotes: false
    
    # Keep important rules enabled
    avoid_relative_lib_imports: true
    always_declare_return_types: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    hash_and_equals: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    valid_regexps: true
