// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows');
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DPEEt2XmWjRFHNW6P2EoxXM1LDj0tWo',
    appId: '1:196733985108:web:9147eb72bec648da5168c1',
    messagingSenderId: '196733985108',
    projectId: 'dompetalumni',
    authDomain: 'dompetalumni.firebaseapp.com',
    storageBucket: 'dompetalumni.firebasestorage.app',
    measurementId: 'G-SFPLFL3YDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DPEEt2XmWjRFHNW6P2EoxXM1LDj0tWo',
    appId: '1:196733985108:android:temp',
    messagingSenderId: '196733985108',
    projectId: 'dompetalumni',
    storageBucket: 'dompetalumni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DPEEt2XmWjRFHNW6P2EoxXM1LDj0tWo',
    appId: '1:196733985108:ios:temp',
    messagingSenderId: '196733985108',
    projectId: 'dompetalumni',
    storageBucket: 'dompetalumni.firebasestorage.app',
    iosBundleId: 'com.example.dompetAlumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DPEEt2XmWjRFHNW6P2EoxXM1LDj0tWo',
    appId: '1:196733985108:ios:temp',
    messagingSenderId: '196733985108',
    projectId: 'dompetalumni',
    storageBucket: 'dompetalumni.firebasestorage.app',
    iosBundleId: 'com.example.dompetAlumni',
  );
}
